### PR TITLE
V2xrelease 7.1 

### PR DESCRIPTION
**Pull request by SaikrishnaBairamoni**
# PR Details
This PR is to merge master into develop with release 7.1 changes
## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[V2XHUB Contributing Guide](https://github.com/usdot-fhwa-OPS/V2X-Hub/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by paulbourelly999** [comment]
@SaikrishnaBairamoni Both docker-compose files on master are still referencing 7.0 images tags. We probably want to update this to be 7.1 but I not sure if that needs to happen before the merge.

**Comment by paulbourelly999** [comment]
@snallamothu It seems we are currently failing the code duplication sonar-scan analysis for the CARMAStreetsPlugin. I assume this is something we can fix later?

**Comment by snallamothu** [comment]
> 

Enter an issue for it to address later.

**Review by paulbourelly999 — APPROVED** [review]
Once PR #325 is closed and merged this looks good to me.

**Pull request merged**
