### PR TITLE
Release/5.0

### PR DESCRIPTION
**Pull request by jtbaird**
PR containing changes for 5.0 release. Changes include but are not limited to:

- TIM, Pedestrian, and Preemption plugins
- build and initialization updates
- documentation updates

### CODE REVIEW

**Comment by jtbaird** [comment]
> Looks good to me. I noticed we didnt change the version number to the environment variable. Can we make sure all the version numbers in manifest files represent 5.0.0 now ?

Per our last discussion I thought we were just changing the `version` value in the manifest.json files to "@PROJECT_VERSION@", and updating the first line of the CMakeLists.txt files to `PROJECT ( CommandPlugin VERSION 5.0 LANGUAGES CXX )`. Is there something we want to change?

**Comment by arayama** [comment]
That is true. I noticed some plugins manifest files remain to have the changes done e.g. BSMLogger.

**Comment by jtbaird** [comment]
> That is true. I noticed some plugins manifest files remain to have the changes done e.g. BSMLogger.

Take another look I think it has the changes are up there

**Comment by arayama** [comment]
Resolved.

**Pull request merged**
