### PR TITLE
Fix timeout error in Spat plugin

### LINKED ISSUE #446: Fix Spat Plugin Socket Handling
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [x] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

In the spat plugin after it times out the messages never are never received again. Also, there is no point in recreating the socket which was overwritten without closing.

### V2XHUB version where this issue was discovered\
Latest

### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

### PR DESCRIPTION
**Pull request by oschwartz10612**
# PR Details
 Fixes after timeout the messages never are never received again.

 Fixes recreating the socket (which in original solution was overwriting without closing).
## Related Issue

Fixes #446

## Motivation and Context

Cleans up socket handling and improves message reception. 

## How Has This Been Tested?

Run in the field for about a week. Plugin is working fine.

## Types of changes

- [ x] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[V2XHUB Contributing Guide](https://github.com/usdot-fhwa-OPS/V2X-Hub/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [] All new and existing tests passed.

### CODE REVIEW

**Comment by rob-baily** [comment]
@oschwartz10612 We believe we have addressed the CI for forked pull requests in the latest version on develop.  Would it be possible for you to merge in the latest from development to your branch?  That should kick off the CI again and we can confirm that it is working and move forward with incorporating this.  Do you have any samples of logs that show the behavior or an easy way to reproduce it?

**Comment by oschwartz10612** [comment]
@rob-baily Sorry it took me a while to get this synced. It should be running the CI now.

**Comment by rob-baily** [comment]
@oschwartz10612 It looks like the CI build passed.  I am going to ask a couple of other folks to review this as I am not that familiar with this code.

**Review by jwillmartin — APPROVED** [review]
Looks good to me and the fix worked!

**Pull request merged**
